### ISSUE TITLE
BehaviorFactory seems overly complicated

### ISSUE THREAD

**Issue by josephnoir** [sblessing/chat-app#7]
Why does the behavior factory use [this](https://github.com/sblessing/chat-app/blob/master/chat.pony#L45) algorithm to choose a behavior? The way it is now, the probability of one action effects all subsequent probabilities. When configuring the input values you have to consider them in the right oder to assess their actual meaning. 

I think it would be much easier to have the probabilities for the actions add up to 100, line them up, roll one dice, and to choose the corresponding action.

**Comment by smarr** [comment]
Yeah, when typing the Newspeak version of the code, I was also wondering whether this is correct.

**Comment by sblessing** [comment]
Indeed. We had this discussion over Slack and the Google Doc previously, and it should make things easier if the probabilities always add up to 100 and the dice role happens exactly once.

**Comment by sblessing** [comment]
Did a pass on this (https://github.com/sblessing/chat-app/commit/6f88757d8a153901eee1e652e963b5d468ec2644), it is not 100% there yet, but this produces "better" behavior. It especially removes the weird behavior when running with a single thread.

@smarr @josephnoir

**Comment by smarr** [comment]
Looks good to me, thanks!

**Comment by josephnoir** [comment]
In https://github.com/sblessing/chat-app/commit/6f88757d8a153901eee1e652e963b5d468ec2644, if leave and invite are both set to 10, we can never have leave actions because both statements will be true and the action will be invite. 

We still need to extend the base probabilities to the whole range. Keeping with the sequence of if statements this could look something like this:

```pony
  new create(compute: U32, post: U32, leave: U32, invite: U32) =>
    _compute = compute
    _post = _compute + post
    _leave = _post + leave
    _invite = _leave + invite

```

*Alternatively* we could subtract from the roll after each check:

```pony
fun box apply(dice: DiceRoll): (Action | None) =>
    vat pick = dice()
    var action: (Action | None) = None

    if pick < _compute then
     return Compute
    end
    pick = pick - _compute
    
    if pick < _post then
      return Post
    end
    pick = pick - _post

    if pick < _leave then
      return Leave
    end
    pick = pick - _leave

    if pick < _invite then
      return Invite
    end

    return None
```

... or did I miss something?

*Edit:* Second suggestion would need return statements.

**Comment by smarr** [comment]
Ah, yes, indeed. We need to spread out the probabilities over the range in some way.

**Comment by sblessing** [comment]
Yes, this was the "not quite there yet"! Change inbound!

**Comment by sblessing** [comment]
Commit https://github.com/sblessing/chat-app/commit/e4e973934d94ba30a693d9d9012ee37fabed5815, note that this only works with a change to the if-statement-chain :)

**Comment by josephnoir** [comment]
Yes, that is correct. Another question: do we want to allow actions to be `None`?

**Comment by sblessing** [comment]
Interesting question, but this is only possible if we make sure that we do not create pathological cases, where, for example, we'd fallback to some other behavior in which case we wouldn't necessarily comply to the individual properties. Also, None is still required, since invitations are racey, so invitations might still bail out with doing nothing (access on empty friendset).

**Comment by smarr** [comment]
Invitations aren't racy, we create a chat for each invite action, no?

**Comment by josephnoir** [comment]
I wasn't arguing to remove `None`. We could require the probabilities to add up to 100, though.

**Comment by sblessing** [comment]
Requiring the probabilities to add up to 100 is already done.

**Comment by sblessing** [comment]
> Invitations aren't racy, we create a chat for each invite action, no?

Yes, but generally, we not know when clients have actually joined that chat! And scheduling has quite an effect of the true completion of the invite.

**Comment by sblessing** [comment]
When we do run the current ^HEAD version of Pony we see something like this:

```
Benchmark                                  i-mean          i-median           i-error          i-stddev
Chat App                               587.074 ms        508.182 ms       ±12.2792 %           208.057
                                           j-mean          j-median           j-error          j-stddev              quality of service
Turns                                  508.142 ms          531.5 ms       ±2.11179 %           175.198                         175.226

Leave        72539
Invite      269371
None        108867
Compute     576829
Post       1274168
```

Although the probabilities add up to 100, None is still being reported because clients might have not been participating in any chats.

That is, any of the following two bail-outs on `act` did apply, because the chat set was empty, causeing [this](https://github.com/sblessing/chat-app/blob/0c9bf59b4348e61896e3a31663c710e8882283bb/chat.pony#L195) to be called:

1. https://github.com/sblessing/chat-app/blob/0c9bf59b4348e61896e3a31663c710e8882283bb/chat.pony#L165 
2. https://github.com/sblessing/chat-app/blob/0c9bf59b4348e61896e3a31663c710e8882283bb/chat.pony#L166 

[None](https://github.com/sblessing/chat-app/blob/0c9bf59b4348e61896e3a31663c710e8882283bb/chat.pony#L192) could not have been picked from the behavior factory, because we will definitely pick a probability with the dice role. Also, [sending no invitations](https://github.com/sblessing/chat-app/blob/0c9bf59b4348e61896e3a31663c710e8882283bb/chat.pony#L183) is counted as an invite.
